CREATE TABLE ACCOUNTS(

    ACCOUNT_NUMBER INT PRIMARY KEY IDENTITY,
    NAME VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    BALANCE DECIMAL(10,2) DEFAULT(0),
    ACCOUNT_TYPE VARCHAR(100),
    OD_LIMIT DECIMAL(10,2) DEFAULT(0)

);